name: DevEnv Infrastructure

on:
  pull_request:

jobs:
  apply:
    name: Apply infrastructure changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Dry run Terraform
        env:
          TF_IN_AUTOMATION: 'true'
          TF_CLI_CONFIG_FILE: .terraformrc
        run: |
          terraform plan
